=== JesusGuerrero/pipeline-schemas/common-canvas/parameter-defs/parameter-defs-v1-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://www.ibm.com/ibm/wdp/property-defs/v1.0/property-defs-schema.json#",
  "title": "Property Definitions Schema",
  "description": "Watson Data Platform Property Definition Schema for the Common Properties editor",
  "type": "object",
  "properties": {
    "current_parameters": {
      "description": "Current parameter set upon input. Keys are parameter names, values are their values.",
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": true
    },
    "parameters": {
      "$ref": "http://www.ibm.com/ibm/wml/operator/v1.0/operator-schema.json#parameters"
    },
    "complex_types": {
      "$ref": "http://www.ibm.com/ibm/wml/operator/v1.0/operator-schema.json#complex_types"
    },
    "uihints": {
      "$ref": "http://www.ibm.com/ibm/wml/uihints/v1.0/uihints-schema.json#"
    },
    "conditions": {
      "$ref": "http://www.ibm.com/ibm/wml/conditions/v1.0/conditions-schema.json#conditions"
    },
    "dataset_metadata": {
      "$ref": "http://www.ibm.com/ibm/wml/dataset-metadata/v1.0/dataset-metadata-schema.json#"
    },
    "resources": {
      "description": "Map of string resources.",
      "type": "object",
      "properties": {},
      "required": [],
      "additionalProperties": true
    }
  },
  "required": [
    "current_parameters",
    "parameters"
  ]
}

=== JesusGuerrero/pipeline-schemas/common-canvas/parameter-defs/examples/Spark_Sample_paramDef.json
{
  "current_parameters": {
    "withReplacement": false,
    "samplingRatio": 1,
    "samplingSize": -1,
    "samplingSeed": -1
  },
  "parameters": [
    {
      "name": "withReplacement",
      "enum": [
        "true",
        "false"
      ],
      "default": false,
      "required": true
    },
    {
      "name": "samplingRatio",
      "type": "double",
      "default": 1,
      "required": true
    },
    {
      "name": "samplingSize",
      "type": "long",
      "default": -1,
      "required": true
    },
    {
      "name": "samplingSeed",
      "type": "integer",
      "default": -1,
      "required": false
    }
  ],
  "uihints": {
    "id": "org.apache.spark.ml.ibm.transformers.Sample",
    "icon": "images/transformationspark.svg",
    "label": {
      "default": "Sample Rows"
    },
    "description": {
      "default": "Perform a simple sample operation on the data, with or without replacement"
    },
    "parameter_info": [
      {
        "parameter_ref": "withReplacement",
        "label": {
          "default": "Sample"
        },
        "description": {
          "default": "Indicate that sampling be performed with replacement"
        },
        "control": "radioset",
        "resource_key": "withReplace"
      },
      {
        "parameter_ref": "samplingRatio",
        "label": {
          "default": "Sample Ratio"
        },
        "description": {
          "default": "Fraction of rows to include in sample"
        }
      },
      {
        "parameter_ref": "samplingSize",
        "label": {
          "default": "Maximum sample size"
        },
        "description": {
          "default": "Maximum number of rows in the sample"
        }
      },
      {
        "parameter_ref": "samplingSeed",
        "label": {
          "default": "Seed"
        },
        "description": {
          "default": "Seed for the sample random number generator"
        },
        "number_generator": {
          "label": {
            "default": "Generate",
            "resource_key": "numberGenerator"
          },
          "range": {
            "min": 1000000,
            "max": 9999999
          }
        }
      }
    ],
    "group_info": [
      {
        "id": "settings",
        "label": {
          "default": "Settings"
        },
        "type": "panels",
        "group_info": [
          {
            "id": "basic-settings",
            "type": "controls",
            "parameter_refs": [
              "withReplacement",
              "samplingRatio"
            ]
          },
          {
            "id": "sample-size",
            "type": "checkboxPanel",
            "label": {
              "default": "Use maximum sample size"
            },
            "parameter_refs": [
              "samplingSize"
            ]
          },
          {
            "id": "sample-seed",
            "type": "checkboxPanel",
            "label": {
              "default": "Repeatable partition assignment"
            },
            "parameter_refs": [
              "samplingSeed"
            ]
          }
        ]
      }
    ]
  },
  "conditions": [
    {
      "validation": {
        "fail_message": {
          "type": "error",
          "focus_parameter_ref": "samplingSize",
          "message": {
            "resource_key": "sampling-size_not_empty"
          }
        },
        "evaluate": {
          "condition": {
            "parameter_ref": "samplingSize",
            "op": "isNotEmpty"
          }
        }
      }
    },
    {
      "validation": {
        "fail_message": {
          "type": "error",
          "focus_parameter_ref": "samplingRatio",
          "message": {
            "resource_key": "sampling-ratio_not_empty"
          }
        },
        "evaluate": {
          "condition": {
            "parameter_ref": "samplingRatio",
            "op": "isNotEmpty"
          }
        }
      }
    }
  ],
  "dataset_metadata": {
    "fields": [
      {
        "name": "Age",
        "type": "integer",
        "metadata": {
          "description": "",
          "measure": "range",
          "modeling_role": "input"
        }
      },
      {
        "name": "Sex",
        "type": "string",
        "metadata": {
          "description": "",
          "measure": "discrete",
          "modeling_role": "input"
        }
      },
      {
        "name": "BP",
        "type": "string",
        "metadata": {
          "description": "",
          "measure": "discrete",
          "modeling_role": "input"
        }
      },
      {
        "name": "Cholesterol",
        "type": "string",
        "metadata": {
          "description": "",
          "measure": "discrete",
          "modeling_role": "input"
        }
      },
      {
        "name": "Na",
        "type": "double",
        "metadata": {
          "description": "",
          "measure": "range",
          "modeling_role": "input"
        }
      },
      {
        "name": "K",
        "type": "double",
        "metadata": {
          "description": "",
          "measure": "range",
          "modeling_role": "input"
        }
      },
      {
        "name": "Drug",
        "type": "string",
        "metadata": {
          "description": "",
          "measure": "discrete",
          "modeling_role": "input"
        }
      }
    ]
  },
  "resources": {
    "org.apache.spark.ml.ibm.transformers.Sample.label": "Sample Rows",
    "org.apache.spark.ml.ibm.transformers.Sample.desc": "Perform a simple sample operation on the data, with or without replacement",
    "withReplacement.label": "Sample",
    "withReplacement.desc": "Indicate that sampling be performed with replacement",
    "withReplace.true.label": "With replacement",
    "withReplace.false.label": "Without replacement",
    "sample-size.label": "Use maximum sample size",
    "sample-seed.label": "Repeatable partition assignment",
    "samplingSize.label": "Maximum sample size",
    "samplingSize.desc": "Maximum number of rows in the sample",
    "samplingRatio.label": "Sample Ratio",
    "samplingRatio.desc": "Fraction of rows to include in sample",
    "samplingSeed.label": "Seed",
    "samplingSeed.desc": "Seed for the sample random number generator",
    "numberGenerator.label": "Generate",
    "numberGenerator.desc": "Generate a random number for use as a seed value",
    "settings.label": "Settings",
    "sampling-size_not_empty": "Select a sampling size",
    "sampling-ratio_not_empty": "Select a sampling ratio"
  }
}
