=== JesusGuerrero/pipeline-schemas/common-pipeline/operators/uihints-v1-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://www.ibm.com/ibm/wdp/uihints/v1.0/uihints-v1-schema.json#",
  "description": "WDP UI Hints schema",
  "title": "WDP UI Hints schema",
  "type": "object",
  "properties": {
    "id": {
      "description": "Operator identifier",
      "type": "string"
    },
    "version": {
      "description": "UIHints schema version",
      "enum": ["1.0"]
    },
    "json_schema": {
      "description": "Refers to the JSON schema used to validate documents of this type",
      "type": "string"
    },
    "label": {
      "description": "External name of operator",
      "type": "object",
      "$ref": "#/definitions/resource_definition"
    },
    "description": {
      "description": "Description of operator",
      "type": "object",
      "$ref": "#/definitions/resource_definition"
    },
    "icon": {
      "description": "URL to operation icon",
      "type": "string"
    },
    "group_info": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/group_definition"
      }
    },
    "editor_size": {
      "description": "Editor size for node edits",
      "enum": [
        "small",
        "medium",
        "large"
      ]
    },
    "parameter_info": {
      "items": {
        "$ref": "#/definitions/parameter_definition"
      },
      "type": "array"
    },
    "complex_type_info": {
      "items": {
        "$ref": "#/definitions/complex_type_definition"
      },
      "type": "array"
    }
  },
  "required": [
    "id",
    "version"
  ],
  "definitions": {
    "group_definition": {
      "description": "Grouping for parameters and groups",
      "type": "object",
      "properties": {
        "id": {
          "description": "Identifier for this group",
          "type": "string"
        },
        "type": {
          "description": "The group type to be displayed",
          "type": "string",
          "enum": [
            "controls",
            "tabs",
            "subTabs",
            "panels",
            "columnAllocation",
            "columnSelection",
            "fieldAllocation",
            "fieldSelection",
            "panelSelector",
            "checkboxPanel"
          ]
        },
        "depends_on_ref": {
          "description": "Parameter name this group depends upon. Valid for panelSelector groups only.",
          "type": "string"
        },
        "label": {
          "description": "Group label",
          "type": "object",
          "$ref": "#/definitions/resource_definition"
        },
        "parameter_refs": {
          "description": "List of parameters to be displayed",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "group_info": {
          "items": {
            "$ref": "#/definitions/group_definition"
          },
          "type": "array"
        }
      },
      "required": [
        "id"
      ]
    },
    "parameter_definition": {
      "description": "Operator parameters hints",
      "type": "object",
      "properties": {
        "parameter_ref": {
          "description": "Parameter reference to base operator parameter definition",
          "type": "string"
        },
        "label": {
          "description": "External name for parameter",
          "type": "object",
          "$ref": "#/definitions/resource_definition"
        },
        "description": {
          "description": "Description of parameter with optional placement context",
          "type": "object",
          "$ref": "#/definitions/placed_resource_definition"
        },
        "control": {
          "description": "Which control to use.  In most cases the control gets to be determined and should not be set",
          "type": "string",
          "enum": [
            "textfield",
            "passwordfield",
            "textarea",
            "expression",
            "numberfield",
            "checkbox",
            "radioset",
            "checkboxset",
            "oneofselect",
            "someofselect",
            "oneofcolumns",
            "someofcolumns",
            "allocatedcolumn",
            "allocatedcolumns",
            "columnselect",
            "allocatedstructures",
            "structuretable",
            "structurelisteditor",
            "toggletext"
          ]
        },
        "orientation": {
          "description": "Determines how the control is displayed",
          "type": "string",
          "enum": [
            "vertical",
            "horizontal"
          ]
        },
        "width": {
          "description": "Percentage of group width the control should use",
          "type": "number"
        },
        "char_limit": {
          "description": "Limits the number of characters a user can enter into the control for string parameters only",
          "type": "number"
        },
        "separator": {
          "description": "Determines where to put a separator relative to the current control",
          "type": "string",
          "enum": [
            "before",
            "after"
          ]
        },
        "visible": {
          "description": "Determines whether to display parameter in control. Used in complex structures",
          "type": "boolean"
        },
        "place_holder_text": {
          "description": "Text hint for the user displayed input controls",
          "type": "object",
          "$ref": "#/definitions/resource_definition"
        },
        "resource_key": {
          "description": "Used as a key for enum value labels",
          "type": "string"
        },
        "edit_style": {
          "description": "Editing style of elements in a table",
          "type": "string",
          "enum": [
            "subpanel",
            "inline"
          ]
        },
        "value_icons": {
          "description": "For enumerated types, this defines the set of icons for the valid values. The ordering must be consistent with the order in the parameter enum attribute.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sortable": {
          "description": "Determines if this column values can be sorted into ascending/descending order in a table. Applies to structure parameters only.",
          "type": "boolean"
        },
        "filterable": {
          "description": "Determines if this column values can be filtered so that only rows that match the filter in column values are shown in the table. Applies to structure parameters only.",
          "type": "boolean"
        },
        "number_generator": {
          "description": "Adds a number generation link beside the label of this control",
          "type": "object",
          "properties": {
            "label": {
              "description": "Link text",
              "type": "object",
              "$ref": "#/definitions/resource_definition"
            },
            "range": {
              "description": "Number generator range",
              "type": "object",
              "properties": {
                "min": {
                  "description": "Maximum value for generated numbers",
                  "type": "number"
                }
              },
              "required": [
                "min",
                "max"
              ]
            }
          },
          "required": [
            "label"
          ]
        }
      },
      "required": [
        "parameter_ref"
      ]
    },
    "complex_type_definition": {
      "type": "object",
      "description": "Complex parameters",
      "properties": {
        "complex_type_ref": {
          "type": "string",
          "description": "Name of complex type, can be referenced in other places."
        },
        "label": {
          "description": "External name used in subpanels",
          "type": "object",
          "$ref": "#/definitions/resource_definition"
        },
        "key_definition": {
          "$ref": "#/definitions/parameter_definition"
        },
        "parameters": {
          "type": "array",
          "description": "List of parameters",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/parameter_definition"
              },
              {
                "$ref": "#/definitions/complex_type_definition"
              }
            ]
          }
        },
        "moveable_rows": {
          "description": "Determines if rows can be moved up or down in a table",
          "type": "boolean"
        }
      },
      "required": [
        "complex_type_ref",
        "parameters"
      ]
    },
    "resource_definition": {
      "description": "Localizable string resource",
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        },
        "resource_key": {
          "type": "string"
        }
      },
      "oneOf": [
        {
          "required": [
            "default"
          ]
        },
        {
          "required": [
            "resource_key"
          ]
        }
      ]
    },
    "placed_resource_definition": {
      "description": "Localizable string resource with optional placement directive",
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        },
        "resource_key": {
          "type": "string"
        },
        "placement": {
          "description": "Optional placement context for the text",
          "enum": [
            "as_tooltip",
            "on_panel"
          ],
          "default": "as_tooltip"
        }
      },
      "oneOf": [
        {
          "required": [
            "default"
          ]
        },
        {
          "required": [
            "resource_key"
          ]
        }
      ]
    }
  }
}

=== JesusGuerrero/pipeline-schemas/common-pipeline/operators/examples/org.apache.spark.ml.ibm.transformers.Sample/uihints.json
{
  "id": "org.apache.spark.ml.ibm.transformers.Sample",
  "version": "1.0",
  "icon": "images/transformationspark.svg",
  "label": {
    "default": "Sample Rows"
  },
  "description": {
    "default": "Perform a simple sample operation on the data, with or without replacement"
  },
  "parameter_info": [
    {
      "parameter_ref": "withReplacement",
      "label": {
        "default": "Sample"
      },
      "description": {
        "default": "Indicate that sampling be performed with replacement"
      },
      "control": "radioset",
      "resource_key": "withReplace"
    },
    {
      "parameter_ref": "samplingRatio",
      "label": {
        "default": "Sample Ratio"
      },
      "description": {
        "default": "Fraction of rows to include in sample"
      }
    },
    {
      "parameter_ref": "samplingSize",
      "label": {
        "default": "Maximum sample size"
      },
      "description": {
        "default": "Maximum number of rows in the sample"
      }
    },
    {
      "parameter_ref": "samplingSeed",
      "label": {
        "default": "Seed"
      },
      "description": {
        "default": "Seed for the sample random number generator"
      },
      "number_generator": {
        "label": {
          "default": "Generate",
          "resource_key": "numberGenerator"
        },
        "range": {
          "min": 1000000,
          "max": 9999999
        }
      }
    }
  ],
  "group_info": [
    {
      "id": "settings",
      "label": {
        "default": "Settings"
      },
      "type": "panels",
      "group_info": [
        {
          "id": "basic-settings",
          "type": "controls",
          "parameter_refs": [
            "withReplacement",
            "samplingRatio"
          ]
        },
        {
          "id": "sample-size",
          "type": "checkboxPanel",
          "label": {
            "default": "Use maximum sample size"
          },
          "parameter_refs": [
            "samplingSize"
          ]
        },
        {
          "id": "sample-seed",
          "type": "checkboxPanel",
          "label": {
            "default": "Repeatable partition assignment"
          },
          "parameter_refs": [
            "samplingSeed"
          ]
        }
      ]
    }
  ]
}
