=== JesusGuerrero/pipeline-schemas/common-pipeline/pipeline-flow/pipeline-flow-v1-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "WDP Pipeline Flow Schema",
  "type": "object",
  "id": "http://www.ibm.com/ibm/wdp/canvas/v1.0/pipeline-flow-v1-schema.json#",
  "properties": {
    "doc_type": {
      "description": "Document type",
      "type": "string"
    },
    "version": {
      "description": "Pipeline-flow schema version",
      "enum": ["1.0"]
    },
    "json_schema": {
      "description": "Refers to the JSON schema used to validate documents of this type",
      "enum": ["http://www.ibm.com/ibm/wdp/canvas/v1.0/pipeline-flow-v1-schema.json"]
    },
    "open_with_tool": {
      "description": "Preferred authoring application",
      "type": "string"
    },
    "id": {
      "description": "Document identifier, GUID recommended",
      "type": "string"
    },
    "primary_pipeline": {
      "description": "Reference to the primary (main) pipeline flow within the document",
      "type": "string"
    },
    "pipelines": {
      "description": "Array of pipelines",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/pipeline_def"
      },
      "uniqueItems": true
    },
    "schemas": {
      "description": "Array of dataset schema used in the document",
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "http://www.ibm.com/ibm/wml/dataset-metadata/v1.0/dataset-metadata-v1-schema.json#/definitions/dataset_schema"
      },
      "uniqueItems": true
    },
    "sources": {
      "description": "Array of source physical data resources",
      "type": "array",
      "items": {
        "$ref": "http://www.ibm.com/ibm/wdp/source-target-pdr/v1.0/source-target-pdr-v1-schema.json#/definitions/common_pipeline_pdr_def"
      },
      "uniqueItems": true
    },
    "targets": {
      "description": "Array of target physical data resources",
      "type": "array",
      "items": {
        "$ref": "http://www.ibm.com/ibm/wdp/source-target-pdr/v1.0/source-target-pdr-v1-schema.json#/definitions/common_pipeline_pdr_def"
      },
      "uniqueItems": true
    },
    "app_data": {
      "$ref": "#/definitions/app_data_def"
    }
  },
  "required": [
    "doc_type",
    "version",
    "primary_pipeline",
    "pipelines"
  ],
  "additionalProperties": false,
  "definitions": {
    "pipeline_def": {
      "description": "Definition of a single pipeline flow",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier",
          "type": "string"
        },
        "runtime": {
          "description": "Runtime associated with the operations in the current pipeline",
          "type": "string"
        },
        "nodes": {
          "description": "Array of pipeline nodes",
          "type": "array",
          "minItems": 0,
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/node_def"
              },
              {
                "$ref": "#/definitions/supernode_def"
              },
              {
                "$ref": "#/definitions/binding_node_def"
              }
            ]
          },
          "uniqueItems": true
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id",
        "runtime",
        "nodes"
      ],
      "additionalProperties": false
    },
    "node_def": {
      "description": "Definition of a single pipeline node",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier for node",
          "type": "string"
        },
        "type": {
          "description": "Node type - always 'execution_node' for pipeline elements",
          "enum": [
            "execution_node"
          ]
        },
        "op": {
          "description": "Operator type identifier",
          "type": "string"
        },
        "inputs": {
          "$ref": "#/definitions/ports_def"
        },
        "outputs": {
          "$ref": "#/definitions/ports_def"
        },
        "parameters": {
          "description": "Input parameters for the operator",
          "type": "object",
          "properties": {},
          "required": [],
          "additionalProperties": true
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id",
        "type",
        "op"
      ],
      "additionalProperties": false
    },
    "supernode_def": {
      "description": "Definition of a supernode which serves as the entry point for a sub-pipeline",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier for the supernode",
          "type": "string"
        },
        "type": {
          "description": "Node type - always 'super_node' for supernode elements",
          "enum": [
            "super_node"
          ]
        },
        "external_pipeline": {
          "description": "Points to an external sub-flow. When not present the sub-flow is assumed to be in the current document",
          "type": "object",
          "properties": {
            "url": {
              "description": "Reference to an external sub-flow",
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        }
      },
      "inputs": {
        "$ref": "#/definitions/pipeline_ports_def"
      },
      "outputs": {
        "$ref": "#/definitions/pipeline_ports_def"
      },
      "app_data": {
        "$ref": "#/definitions/app_data_def"
      }
    },
    "required": [
      "id",
      "type"
    ],
    "additionalProperties": false
  },
  "binding_node_def": {
    "description": "Defines an entry or exit point (source or sink) for a pipeline. Bindings can be concrete: the concrete_binding element is present on the port; or bindings can be abstract: bindings are performed externally via configuration or a wrapper document.",
    "type": "object",
    "oneOf": [
      {
        "properties": {
          "id": {
            "description": "Unique identifier for the binding",
            "type": "string"
          },
          "type": {
            "description": "Node type - always 'binding' for binding elements",
            "enum": [
              "binding"
            ]
          },
          "input": {
            "$ref": "#/definitions/port_binding_def"
          },
          "app_data": {
            "$ref": "#/definitions/app_data_def"
          }
        }
      },
      {
        "properties": {
          "id": {
            "description": "Unique identifier for the binding",
            "type": "string"
          },
          "type": {
            "description": "Node type - always 'binding' for binding elements",
            "enum": [
              "binding"
            ]
          },
          "output": {
            "$ref": "#/definitions/port_binding_def"
          },
          "app_data": {
            "$ref": "#/definitions/app_data_def"
          }
        }
      }
    ],
    "required": [
      "id",
      "type"
    ],
    "additionalProperties": false
  },
  "port_def": {
    "description": "Port definition (input/output) on a node",
    "type": "object",
    "properties": {
      "id": {
        "description": "Unique identifier",
        "type": "string"
      },
      "schema_ref": {
        "description": "Optional dataset schema reference associated with the port",
        "type": "string"
      },
      "links": {
        "description": "Array of links going into the node. Applies to input ports and exit bindings only.",
        "type": "array",
        "minItems": 0,
        "items": {
          "$ref": "#/definitions/link_def"
        },
        "uniqueItems": true
      },
      "app_data": {
        "$ref": "#/definitions/app_data_def"
      }
    },
    "required": [
      "id"
    ],
    "additionalProperties": false
  },
  "port_binding_def": {
    "description": "Definition (input/output) of a port on a binding node (bound or unbound). If no binding is present the port is bound at runtime via a configuration object or wrapper document.",
    "type": "object",
    "properties": {
      "id": {
        "description": "Unique identifier",
        "type": "string"
      },
      "external_binding": {
        "description": "Concrete data binding to a source or a sink. Additional properties that are specific to the binding type go here.",
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": true
      },
      "schema_ref": {
        "description": "Optional dataset schema associated with port",
        "type": "string"
      },
      "link": {
        "$ref": "#/definitions/link_def"
      },
      "app_data": {
        "$ref": "#/definitions/app_data_def"
      }
    },
    "required": [
      "id"
    ],
    "additionalProperties": false
  },
  "ports_def": {
    "type": "array",
    "minItems": 1,
    "items": {
      "$ref": "#/definitions/port_def"
    },
    "uniqueItems": true
  },
  "pipeline_ports_def": {
    "type": "array",
    "minItems": 1,
    "items": {
      "$ref": "#/definitions/pipeline_port_def"
    },
    "uniqueItems": true
  },
  "pipeline_port_def": {
    "description": "Supernode port definition (input/output) with pipeline port binding",
    "type": "object",
    "properties": {
      "id": {
        "description": "Unique identifier",
        "type": "string"
      },
      "schema_ref": {
        "description": "Optional dataset schema associated with port",
        "type": "string"
      },
      "links": {
        "description": "Array of links in the current pipeline going in to or out of the port",
        "type": "array",
        "minItems": 0,
        "items": {
          "$ref": "#/definitions/link_def"
        },
        "uniqueItems": true
      },
      "pipeline_link_ref": {
        "description": "Binding to another pipeline, which can be either within the current document or in an external document",
        "$ref": "#/definitions/pipeline_link_def"
      },
      "app_data": {
        "$ref": "#/definitions/app_data_def"
      }
    },
    "required": [
      "id"
    ],
    "additionalProperties": false
  },
  "link_def": {
    "description": "Node link definition",
    "type": "object",
    "properties": {
      "node_id_ref": {
        "description": "id of a node this link connects to",
        "type": "string"
      },
      "port_id_ref": {
        "description": "Optional port id of the node this link connects to. Not required when linking to nodes with only a single port.",
        "type": "string"
      },
      "app_data": {
        "$ref": "#/definitions/app_data_def"
      }
    },
    "required": [
      "node_id_ref"
    ],
    "additionalProperties": false
  },
  "pipeline_link_def": {
    "description": "Pipeline link definition",
    "type": "object",
    "properties": {
      "pipeline_id_ref": {
        "description": "Required id of the pipeline this link connects to",
        "type": "string"
      },
      "node_id_ref": {
        "description": "Required id of the node this link connects to",
        "type": "string"
      },
      "port_id_ref": {
        "description": "Optional port id of a node this link connects to. Not required when linking to nodes with only a single port.",
        "type": "string"
      },
      "app_data": {
        "$ref": "#/definitions/app_data_def"
      }
    },
    "required": [
      "pipeline_id_ref",
      "node_id_ref"
    ],
    "additionalProperties": false
  },
  "app_data_def": {
    "description": "Object containing app-specific data",
    "type": "object",
    "properties": {
      "ui_data": {
        "oneOf": [
          {
            "$ref": "http://www.ibm.com/ibm/wdp/canvas/v1.0/pipeline-flow-ui-schema.json#/definitions/pipeline_overview"
          },
          {
            "$ref": "http://www.ibm.com/ibm/wdp/canvas/v1.0/pipeline-flow-ui-schema.json#/definitions/pipeline_def"
          },
          {
            "$ref": "http://www.ibm.com/ibm/wdp/canvas/v1.0/pipeline-flow-ui-schema.json#/definitions/port_info_def"
          },
          {
            "$ref": "http://www.ibm.com/ibm/wdp/canvas/v1.0/pipeline-flow-ui-schema.json#/definitions/node_info_def"
          }
        ]
      }
    },
    "required": [],
    "additionalProperties": true
  }
}

=== JesusGuerrero/pipeline-schemas/common-pipeline/pipeline-flow/examples/pipeline-flow-v1-example-simple.json
{
  "doc_type": "pipeline",
  "version": "1.0",
  "id": "24cc9881-f83a-4d38-b15b-8bf541e100fb",
  "app_data": {
    "ui_data": {
      "name": "Simple Pipeline Flow Example",
      "description": {
        "default": "A basic example pipeline - just does load/filter/save"
      },
      "class_name": "pipeline-flow-overall"
    },
    "wml_data": {
      "typeId": "stream"
    }
  },
  "primary_pipeline": "simple-pipeline",
  "pipelines": [
    {
      "id": "simple-pipeline",
      "runtime": "scala-spark-2.0.1",
      "app_data": {
        "ui_data": {
          "zoom": 100,
          "comments": []
        }
      },
      "nodes": [
        {
          "id": "entryID1PE",
          "type": "binding",
          "output": {
            "id": "entryPort1PE",
            "schema_ref": "schema1"
          },
          "connection":{
            "ref":"d7c75790-90fc-4883-a5fc-3bb589166a52",
            "project_ref":"0a0a20e8-e8a8-4710-b90a-6df3ff775b04",
            "properties": {
              "schema_name":"GOSALES",
              "table_name":"PRODUCT_NAME_LOOKUP"
            }
          }
        },
        {
          "id": "nodeID2PE",
          "type": "execution_node",
          "op": "org.apache.spark.ml.ibm.transformers.FilterColumns",
          "inputs": [
            {
              "id": "input1NodeID2PE",
              "schema_ref": "schema1",
              "links": [
                {
                  "node_id_ref": "entryID1PE"
                }
              ],
              "app_data": {
                "ui_data": {
                  "label": {
                    "default": "input 1 Node ID2PE"
                  }
                }
              }
            }
          ],
          "outputs": [
            {
              "id": "output1NodeID2PE",
              "schema_ref": "schema2",
              "app_data": {
                "ui_data": {
                  "label": {
                    "default": "output 1 Node ID2PE"
                  }
                }
              }
            }
          ],
          "parameters": {
            "dropColumns": [
              "integer2",
              "double4"
            ]
          },
          "app_data": {
            "ui_data": {
              "label": {
                "default": "Filter"
              },
              "description": {
                "default": "Filter columns"
              },
              "image": "filter-columns.svg",
              "x_pos": 784,
              "y_pos": 202,
              "class_name": "nodes"
            },
            "wml_data": {
              "typeId": "filter-columns"
            }
          }
        },
        {
          "id": "exitID1PE",
          "type": "binding",
          "input": {
            "id": "exitPort1PE",
            "schema_ref": "schema2",
            "link": {
              "node_id_ref": "nodeID2PE"
            },
            "app_data": {
              "ui_data": {
                "label": {
                  "default": "exit Port 1PE"
                }
              }
            }
          },
          "data_asset":{
            "properties":{
              "name": "employee_data.csv"
            }
          }
        }
      ]
    }
  ],
  "schemas": [
    {
      "id": "schema1",
      "fields": [
        {
          "name": "integer2",
          "type": "integer",
          "nullable": false,
          "metadata": {
            "description": "Field integer2 is an integer field",
            "measure": "range",
            "modeling_role": "input",
            "range": {
              "min": -1,
              "max": 400
            }
          }
        },
        {
          "name": "double4",
          "type": "double",
          "nullable": false,
          "metadata": {
            "description": "Field double4 is a double field",
            "measure": "range",
            "modeling_role": "input",
            "range": {
              "min": 0.101,
              "max": 100.211
            }
          }
        },
        {
          "name": "string1",
          "type": "string",
          "nullable": true,
          "metadata": {
            "description": "Field string1 is a string field",
            "measure": "set",
            "modeling_role": "input",
            "max_length": 24,
            "values": [
              "One",
              "Two",
              "Three"
            ]
          }
        }
      ]
    },
    {
      "id": "schema2",
      "fields": [
        {
          "name": "string1",
          "type": "string",
          "nullable": true,
          "metadata": {
            "description": "Field string1 is a string field",
            "measure": "set",
            "modeling_role": "input",
            "max_length": 24,
            "values": [
              "One",
              "Two",
              "Three"
            ]
          }
        }
      ]
    }
  ]
}
